---
title: "Notes"
output: html_document
---

# General Shared Notes about the project 

## P

the prosentage of student passing the target test level and prosentage of students who move on to HAVO is a positive correlation. However, school with more disadvantage with teh same passing score, end up being less adviced to HAVO, see plot. 

1. Considering making the visualization into an interactive plot that moves from one line showing the correlation for a "general" school weight value, and then you can press something that allows to see the relationship at different school weight values.

2. How can we incorporate test providers into this picture? What would that tell us about the data and results. 

3. Create a predictive model that looks at test results predicting the school a kid is going to. Then get those predictions and actually compare them to the real school advice. If these residuals are large (low accuracy) than there might be something else that's influencing what school a child is sent to.
Maybe if we  include then a second predictor in the model, which is "school weights" to see weather the model accuracy increases, when comparing predicted and obs school advice. 
This would then allow us to move further and see how school weight differentiates. 




## Part 2 

### Final Tweaks To D0
Things to fix 
- x-axis same scale as y-axis 
- remove typical line 
- make sure the titles are well aligned (seems to be too much at the top)
- colors
- higlight area between the two outer lines? 

Things to add
- highlight (sub)title 
- add an informative note and the source 
  e.g. what is disadvantaged? 
- add confidence interval 
- maybe adjust axis texts and title (do this last)
- 





